# APIサーバーのテスト用コマンド

# GET http://localhost:8080/building?bn=10号館大講義

# GET http://localhost:8080/classroom?rn=G2210

# GET http://localhost:8080/subject?sn=mk

# GET http://localhost:8080/coordinate?fr=10号館&to=4号館


# POST http://localhost:8080/building HTTP/1.1
# content-type: application/json

# {"name":"10号館大講義"}

# POST http://localhost:8080/classroom HTTP/1.1
# content-type: application/json

# {"name":"G2210"}

# POST http://localhost:8080/subject HTTP/1.1
# content-type: application/json

# { "name":"演習" }
