
# GET http://localhost:8080/

# POST http://localhost:8080/building HTTP/1.1
# content-type: application/json

# {"name":"言語文化研究室"}

# POST http://localhost:8080/classroom HTTP/1.1
# content-type: application/json

# {"name":"プレゼンテーションルーム2"}

POST http://localhost:8080/subject HTTP/1.1
content-type: application/json

{ "name":"人工知能" }
