# APIサーバーのテスト用コマンド
# GET http://localhost:8080/

# POST http://localhost:8080/building HTTP/1.1
# content-type: application/json

# {"name":"10号館大講義室"}

# POST http://localhost:8080/classroom HTTP/1.1
# content-type: application/json

# {"name":"大講義"}

POST http://localhost:8080/subject HTTP/1.1
content-type: application/json

{ "name":"人工知能" }
