version: "3"
services:
  go:
    container_name: koukaten2022_GO
    build:
      context: ./docker/go
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    env_file:
      - ./Docker/go/.env
    volumes:
      - ./go:/go/src/app # マウントディレクトリ
    ports:
      - 8080:8080
    depends_on:
      - "mysql"

  mysql:
    container_name: koukaten2022_DB
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: admin
    depends_on:
      - "neo4j"

  neo4j:
    container_name: koukaten2022_NEO4J
    build:
      context: ./docker/neo4j
      dockerfile: Dockerfile
    restart: always
    extra_hosts: 
      - localhost:172.20.0.1 
    ports:
      - 57474:7474
      - 57687:7687
    volumes:
      - ./docker/neo4j/volumes/neo4j/data:/data
