version: "3"
services:
  # go:
  #   container_name: koukaten2022_GO
  #   build:
  #     context: ./docker/app
  #     dockerfile: Dockerfile
  #   stdin_open: true
  #   tty: true
  #   env_file:
  #     - ./Docker/app/.env
  #   volumes:
  #     - type: bind
  #       source: ./go
  #       target: /go/app
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - "mysql"
    

  mysql:
    container_name: koukaten2022_DB
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: admin
